### PR TITLE
Add 2x mailing_list and 1x pmid info

### PR DESCRIPTION
**Pull request by abremges**
velvet and soap have mailing lists/forums, and megahit is published by now

### CODE REVIEW

**Comment by abremges** [comment]
@michaelbarton @pbelmann can either of you trigger a rebuild of bioboxes.org? It still shows outdated info here: http://bioboxes.org/available-bioboxes/
With velvet on top, which used to have one of the most active mailing lists, and the commentary published, I believe this should be updated in a timely manner.

**Comment by abremges** [comment]
By the way, why did you disable Issues for https://github.com/bioboxes/bioboxes.org?

**Comment by michaelbarton** [comment]
I've triggered a rebuild of bioboxes.org. A rebuild is not automatically triggered because this repo is not linked the bioboxes.org on the CI server.

**Comment by michaelbarton** [comment]
The issues are disable on the bioboxes/bioboxes.org because we have been discussing the website on the [rfc repository issue tracker](https://github.com/bioboxes/rfc/issues?utf8=%E2%9C%93&q=+label%3AA-Website+).

**Pull request merged**
